# Generated by Django 5.0.6 on 2026-03-11 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('nic', models.CharField(max_length=20, null=True, unique=True, verbose_name='NIC')),
                ('address', models.TextField()),
                ('designation', models.CharField(default='', max_length=100)),
                ('staff_mobile', models.CharField(default='', max_length=20, verbose_name='Staff Mobile')),
                ('photo', models.ImageField(upload_to='employee_photos/')),
                ('QR_Link', models.URLField(blank=True, default='', null=True)),
                ('qr_code', models.ImageField(blank=True, editable=False, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('manager_name', models.CharField(default='', max_length=100, verbose_name="Direct Report's Name")),
                ('manager_mobile', models.CharField(default='', max_length=20, verbose_name="Direct Report's Mobile Number")),
            ],
            options={
                'verbose_name': 'Staff Verification',
                'verbose_name_plural': 'Staff Verification',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('company_name', models.CharField(blank=True, help_text='Name of the company the implementation is for', max_length=255, null=True, verbose_name='Company Name')),
                ('company_logo', models.ImageField(blank=True, help_text='Upload the company logo', null=True, upload_to='company_logo/', verbose_name='Company Logo')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
