# Generated by Django 5.0.6 on 2026-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='QR_Link',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Website'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qr_link',
            field=models.URLField(blank=True, null=True, verbose_name='QR Link'),
        ),
    ]
